import { Challenge, University, Faculty, Student, IndustryPartner, Project, Notification, DistrictData, ChallengeCategory, ChallengePriority } from './types';

// ─── DISTRICTS ───────────────────────────────────────────────────────────────

export const districts: DistrictData[] = [
  { id: 'ranchi', name: 'Ranchi', challenges: 142, highPriority: 38, validated: 89, projects: 31, deployed: 7, beneficiaries: 8400, lat: 23.3441, lng: 85.3096 },
  { id: 'dhanbad', name: 'Dhanbad', challenges: 118, highPriority: 29, validated: 72, projects: 24, deployed: 5, beneficiaries: 6200, lat: 23.7957, lng: 86.4304 },
  { id: 'bokaro', name: 'Bokaro', challenges: 97, highPriority: 24, validated: 61, projects: 19, deployed: 4, beneficiaries: 4800, lat: 23.6693, lng: 86.1511 },
  { id: 'deoghar', name: 'Deoghar', challenges: 84, highPriority: 21, validated: 54, projects: 16, deployed: 3, beneficiaries: 3600, lat: 24.4854, lng: 86.6944 },
  { id: 'dumka', name: 'Dumka', challenges: 76, highPriority: 19, validated: 48, projects: 14, deployed: 2, beneficiaries: 2900, lat: 24.2674, lng: 87.2501 },
  { id: 'hazaribagh', name: 'Hazaribagh', challenges: 89, highPriority: 22, validated: 57, projects: 18, deployed: 3, beneficiaries: 4100, lat: 23.9925, lng: 85.3637 },
  { id: 'giridih', name: 'Giridih', challenges: 71, highPriority: 17, validated: 44, projects: 12, deployed: 2, beneficiaries: 2600, lat: 24.1853, lng: 86.3088 },
  { id: 'palamu', name: 'Palamu', challenges: 93, highPriority: 26, validated: 59, projects: 17, deployed: 3, beneficiaries: 3800, lat: 24.0291, lng: 84.0676 },
  { id: 'east_singhbhum', name: 'East Singhbhum', challenges: 108, highPriority: 27, validated: 68, projects: 22, deployed: 5, beneficiaries: 5800, lat: 22.8046, lng: 86.2029 },
  { id: 'west_singhbhum', name: 'West Singhbhum', challenges: 86, highPriority: 21, validated: 54, projects: 16, deployed: 3, beneficiaries: 3500, lat: 22.1461, lng: 85.5953 },
  { id: 'simdega', name: 'Simdega', challenges: 62, highPriority: 15, validated: 39, projects: 10, deployed: 1, beneficiaries: 2100, lat: 22.6139, lng: 84.5023 },
  { id: 'lohardaga', name: 'Lohardaga', challenges: 48, highPriority: 11, validated: 31, projects: 8, deployed: 1, beneficiaries: 1700, lat: 23.4358, lng: 84.6841 },
  { id: 'gumla', name: 'Gumla', challenges: 67, highPriority: 16, validated: 42, projects: 11, deployed: 2, beneficiaries: 2400, lat: 23.0443, lng: 84.5406 },
  { id: 'latehar', name: 'Latehar', challenges: 54, highPriority: 14, validated: 34, projects: 9, deployed: 1, beneficiaries: 1900, lat: 23.7444, lng: 84.5011 },
  { id: 'chatra', name: 'Chatra', challenges: 59, highPriority: 14, validated: 37, projects: 10, deployed: 1, beneficiaries: 2000, lat: 24.2055, lng: 84.8730 },
];

// ─── UNIVERSITIES ────────────────────────────────────────────────────────────

export const universities: University[] = [
  {
    id: 'bit-mesra',
    name: 'Birla Institute of Technology, Mesra',
    shortName: 'BIT Mesra',
    district: 'Ranchi',
    type: 'Deemed University',
    departments: ['Civil Engineering', 'Computer Science', 'Electronics', 'Environmental Engineering', 'Biotechnology', 'Architecture'],
    researchAreas: ['IoT', 'Water Quality', 'Machine Learning', 'GIS', 'Renewable Energy', 'Smart Cities'],
    labs: ['IoT Research Lab', 'Environmental Testing Lab', 'GIS Lab', 'AI/ML Lab', 'Embedded Systems Lab'],
    facultyCount: 248,
    studentCount: 4200,
    hasInnovationCenter: true,
    activeProjects: 18,
    completedProjects: 42,
    matchScore: 94,
    matchReasons: ['Environmental Engineering', 'IoT Lab', 'Water Research', 'GIS capability', 'Similar previous projects'],
  },
  {
    id: 'nit-jamshedpur',
    name: 'National Institute of Technology, Jamshedpur',
    shortName: 'NIT Jamshedpur',
    district: 'East Singhbhum',
    type: 'National Institute',
    departments: ['Mechanical Engineering', 'Civil Engineering', 'Computer Science', 'Metallurgy', 'Production Engineering'],
    researchAreas: ['Manufacturing', 'Materials Science', 'Structural Engineering', 'Data Analytics', 'Robotics'],
    labs: ['Advanced Manufacturing Lab', 'Structural Lab', 'Robotics Lab', 'Data Science Lab'],
    facultyCount: 189,
    studentCount: 3800,
    hasInnovationCenter: true,
    activeProjects: 14,
    completedProjects: 31,
    matchScore: 89,
    matchReasons: ['Civil Engineering', 'Data Analytics', 'Structural expertise', 'Industry partnerships'],
  },
  {
    id: 'iit-ism-dhanbad',
    name: 'IIT (ISM) Dhanbad',
    shortName: 'IIT ISM',
    district: 'Dhanbad',
    type: 'IIT',
    departments: ['Mining Engineering', 'Environmental Engineering', 'Computer Science', 'Petroleum Engineering', 'Applied Geology'],
    researchAreas: ['Mining Technology', 'Environmental Remediation', 'Underground Water', 'Sensor Networks', 'Remote Sensing'],
    labs: ['Mine Safety Lab', 'Environmental Monitoring Lab', 'Remote Sensing Lab', 'Sensor Lab'],
    facultyCount: 312,
    studentCount: 5600,
    hasInnovationCenter: true,
    activeProjects: 24,
    completedProjects: 67,
    matchScore: 81,
    matchReasons: ['Environmental Engineering', 'Sensor Networks', 'Water Research', 'Remote Sensing'],
  },
  {
    id: 'ranchi-university',
    name: 'Ranchi University',
    shortName: 'RU Ranchi',
    district: 'Ranchi',
    type: 'State University',
    departments: ['Agriculture', 'Environmental Science', 'Computer Applications', 'Social Work', 'Public Health'],
    researchAreas: ['Rural Development', 'Tribal Welfare', 'Agricultural Extension', 'Community Health', 'Natural Resources'],
    labs: ['Agricultural Research Lab', 'Public Health Lab', 'Social Research Centre'],
    facultyCount: 156,
    studentCount: 12000,
    hasInnovationCenter: false,
    activeProjects: 8,
    completedProjects: 19,
    matchScore: 76,
    matchReasons: ['Rural Development', 'Community Research', 'Social Impact'],
  },
  {
    id: 'xlri-jamshedpur',
    name: 'XLRI Xavier School of Management',
    shortName: 'XLRI',
    district: 'East Singhbhum',
    type: 'Deemed University',
    departments: ['Business Management', 'Human Resources', 'Social Enterprise', 'Healthcare Management'],
    researchAreas: ['Social Entrepreneurship', 'CSR', 'Impact Assessment', 'Rural Management', 'Healthcare Systems'],
    labs: ['Social Enterprise Lab', 'Impact Analytics Centre'],
    facultyCount: 87,
    studentCount: 1200,
    hasInnovationCenter: true,
    activeProjects: 6,
    completedProjects: 14,
    matchScore: 72,
    matchReasons: ['Impact Assessment', 'Social Enterprise', 'CSR Management'],
  },
  {
    id: 'jsac',
    name: 'Jharkhand Space Applications Centre',
    shortName: 'JSAC',
    district: 'Ranchi',
    type: 'Research Institute',
    departments: ['Remote Sensing', 'GIS', 'Spatial Analytics', 'Disaster Management'],
    researchAreas: ['Satellite Imagery', 'Land Use', 'Flood Mapping', 'Crop Monitoring', 'Urban Planning'],
    labs: ['GIS Lab', 'Remote Sensing Lab', 'Drone Lab', 'Geospatial AI Lab'],
    facultyCount: 64,
    studentCount: 0,
    hasInnovationCenter: false,
    activeProjects: 12,
    completedProjects: 28,
    matchScore: 88,
    matchReasons: ['GIS expertise', 'Remote Sensing', 'Spatial Analytics', 'Jharkhand-specific data'],
  },
  {
    id: 'gla-university',
    name: 'Central University of Jharkhand',
    shortName: 'CUJ',
    district: 'Ranchi',
    type: 'Central University',
    departments: ['Environmental Science', 'Tribal Studies', 'Mass Communication', 'Nanotechnology', 'Integrated Science'],
    researchAreas: ['Tribal Community Research', 'Environmental Policy', 'Nano-materials', 'Biodiversity', 'Forest Resources'],
    labs: ['Tribal Research Centre', 'Environmental Science Lab', 'Nanotechnology Lab'],
    facultyCount: 128,
    studentCount: 4800,
    hasInnovationCenter: false,
    activeProjects: 7,
    completedProjects: 12,
    matchScore: 68,
    matchReasons: ['Environmental Science', 'Community Research', 'Policy Expertise'],
  },
  {
    id: 'jharkhand-rai-university',
    name: 'Jharkhand Rai University',
    shortName: 'JRU',
    district: 'Ranchi',
    type: 'Private University',
    departments: ['Engineering', 'Medical Sciences', 'Agriculture', 'Pharmacy', 'Management'],
    researchAreas: ['Agricultural Technology', 'Healthcare Innovation', 'Pharmaceutical Research'],
    labs: ['Agriculture Lab', 'Medical Research Lab', 'Pharmacy Lab'],
    facultyCount: 176,
    studentCount: 8200,
    hasInnovationCenter: false,
    activeProjects: 5,
    completedProjects: 9,
    matchScore: 63,
    matchReasons: ['Agriculture', 'Healthcare', 'Applied Research'],
  },
  {
    id: 'bau-ranchi',
    name: 'Birsa Agricultural University',
    shortName: 'BAU Ranchi',
    district: 'Ranchi',
    type: 'Agricultural University',
    departments: ['Agronomy', 'Horticulture', 'Soil Science', 'Plant Pathology', 'Agricultural Economics'],
    researchAreas: ['Soil Health', 'Crop Varieties', 'Irrigation', 'Pesticide Management', 'Tribal Farming'],
    labs: ['Soil Testing Lab', 'Seed Technology Lab', 'Crop Research Farm'],
    facultyCount: 142,
    studentCount: 3200,
    hasInnovationCenter: false,
    activeProjects: 11,
    completedProjects: 26,
    matchScore: 79,
    matchReasons: ['Agriculture expertise', 'Soil Research', 'Tribal Farming Systems'],
  },
  {
    id: 'rims',
    name: 'Rajendra Institute of Medical Sciences',
    shortName: 'RIMS',
    district: 'Ranchi',
    type: 'Medical Institute',
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Public Health', 'Community Medicine'],
    researchAreas: ['Public Health', 'Community Healthcare', 'Tropical Medicine', 'Telemedicine', 'Rural Health'],
    labs: ['Public Health Lab', 'Epidemiology Centre', 'Telemedicine Centre'],
    facultyCount: 268,
    studentCount: 2800,
    hasInnovationCenter: false,
    activeProjects: 9,
    completedProjects: 17,
    matchScore: 85,
    matchReasons: ['Healthcare expertise', 'Community Medicine', 'Rural Health Research'],
  },
];

// ─── FACULTY ─────────────────────────────────────────────────────────────────

export const faculty: Faculty[] = [
  { id: 'f1', name: 'Dr. Anjali Sharma', designation: 'Associate Professor', department: 'Environmental Engineering', universityId: 'bit-mesra', expertise: ['Water Quality', 'IoT Sensors', 'Environmental Monitoring'], publications: 42, activeProjects: 2, email: 'anjali.sharma@bitmesra.ac.in' },
  { id: 'f2', name: 'Prof. Rajesh Kumar', designation: 'Professor', department: 'Civil Engineering', universityId: 'bit-mesra', expertise: ['Water Resources', 'Hydrology', 'GIS'], publications: 67, activeProjects: 3, email: 'rajesh.kumar@bitmesra.ac.in' },
  { id: 'f3', name: 'Dr. Sunita Patel', designation: 'Assistant Professor', department: 'Computer Science', universityId: 'bit-mesra', expertise: ['Machine Learning', 'Data Science', 'AI'], publications: 28, activeProjects: 2, email: 'sunita.patel@bitmesra.ac.in' },
  { id: 'f4', name: 'Prof. Arun Mishra', designation: 'Professor', department: 'Mining Engineering', universityId: 'iit-ism-dhanbad', expertise: ['Environmental Remediation', 'Sensor Networks'], publications: 89, activeProjects: 4, email: 'arun.mishra@iitism.ac.in' },
  { id: 'f5', name: 'Dr. Priya Singh', designation: 'Associate Professor', department: 'Civil Engineering', universityId: 'nit-jamshedpur', expertise: ['Structural Engineering', 'Infrastructure'], publications: 34, activeProjects: 2, email: 'priya.singh@nitjsr.ac.in' },
  { id: 'f6', name: 'Dr. Mohan Gupta', designation: 'Associate Professor', department: 'Agriculture', universityId: 'bau-ranchi', expertise: ['Soil Science', 'Crop Technology', 'Irrigation'], publications: 51, activeProjects: 3, email: 'mohan.gupta@bau.ac.in' },
  { id: 'f7', name: 'Dr. Rekha Verma', designation: 'Professor', department: 'Public Health', universityId: 'rims', expertise: ['Community Health', 'Epidemiology', 'Telemedicine'], publications: 73, activeProjects: 2, email: 'rekha.verma@rims.jharkhand.gov.in' },
  { id: 'f8', name: 'Dr. Vikram Tiwari', designation: 'Assistant Professor', department: 'Computer Science', universityId: 'nit-jamshedpur', expertise: ['IoT', 'Embedded Systems', 'Data Analytics'], publications: 19, activeProjects: 1, email: 'vikram.tiwari@nitjsr.ac.in' },
  { id: 'f9', name: 'Prof. Geeta Mahato', designation: 'Professor', department: 'Environmental Science', universityId: 'gla-university', expertise: ['Tribal Ecology', 'Forest Resources', 'Biodiversity'], publications: 45, activeProjects: 2, email: 'geeta.mahato@cuj.ac.in' },
  { id: 'f10', name: 'Dr. Sanjay Oraon', designation: 'Associate Professor', department: 'Remote Sensing', universityId: 'jsac', expertise: ['GIS', 'Satellite Imagery', 'Spatial Analysis'], publications: 38, activeProjects: 3, email: 'sanjay.oraon@jsac.jharkhand.gov.in' },
  { id: 'f11', name: 'Dr. Amit Ranjan', designation: 'Assistant Professor', department: 'Electronics', universityId: 'bit-mesra', expertise: ['Embedded Systems', 'FPGA', 'Signal Processing'], publications: 22, activeProjects: 1, email: 'amit.ranjan@bitmesra.ac.in' },
  { id: 'f12', name: 'Prof. Kavita Sinha', designation: 'Professor', department: 'Social Work', universityId: 'ranchi-university', expertise: ['Community Development', 'Rural Welfare', 'Tribal Rights'], publications: 56, activeProjects: 2, email: 'kavita.sinha@ru.ac.in' },
  { id: 'f13', name: 'Dr. Narendra Prasad', designation: 'Associate Professor', department: 'Horticulture', universityId: 'bau-ranchi', expertise: ['Vegetable Farming', 'Organic Agriculture', 'Market Linkages'], publications: 29, activeProjects: 2, email: 'narendra.prasad@bau.ac.in' },
  { id: 'f14', name: 'Dr. Meenakshi Devi', designation: 'Assistant Professor', department: 'Healthcare Management', universityId: 'xlri-jamshedpur', expertise: ['Health Systems', 'Impact Assessment', 'Rural Healthcare'], publications: 16, activeProjects: 1, email: 'meenakshi.devi@xlri.ac.in' },
  { id: 'f15', name: 'Prof. Deepak Srivastava', designation: 'Professor', department: 'Civil Engineering', universityId: 'bit-mesra', expertise: ['Water Supply', 'Sanitation', 'Urban Planning'], publications: 61, activeProjects: 3, email: 'deepak.srivastava@bitmesra.ac.in' },
];

// ─── STUDENTS ─────────────────────────────────────────────────────────────────

export const students: Student[] = [
  { id: 's1', name: 'Rahul Kumar', rollNumber: 'BIT/CE/2023/001', department: 'Civil Engineering', year: 3, universityId: 'bit-mesra', skills: ['AutoCAD', 'Water Quality Testing', 'MATLAB'] },
  { id: 's2', name: 'Ananya Mishra', rollNumber: 'BIT/CS/2023/042', department: 'Computer Science', year: 3, universityId: 'bit-mesra', skills: ['Python', 'Machine Learning', 'Data Visualization'] },
  { id: 's3', name: 'Aman Sinha', rollNumber: 'BIT/EE/2023/017', department: 'Electronics Engineering', year: 3, universityId: 'bit-mesra', skills: ['Arduino', 'Raspberry Pi', 'IoT Protocols'] },
  { id: 's4', name: 'Priya Kumari', rollNumber: 'BIT/CS/2024/008', department: 'Computer Science', year: 2, universityId: 'bit-mesra', skills: ['UI/UX Design', 'Figma', 'React.js'] },
  { id: 's5', name: 'Deepak Oraon', rollNumber: 'BIT/EN/2023/031', department: 'Environmental Engineering', year: 3, universityId: 'bit-mesra', skills: ['Water Testing', 'Environmental Sampling', 'GIS'] },
  { id: 's6', name: 'Sunita Murmu', rollNumber: 'NIT/CS/2023/019', department: 'Computer Science', year: 3, universityId: 'nit-jamshedpur', skills: ['Java', 'Android Development', 'Backend APIs'] },
  { id: 's7', name: 'Rohan Mahato', rollNumber: 'NIT/ME/2023/054', department: 'Mechanical Engineering', year: 3, universityId: 'nit-jamshedpur', skills: ['3D Printing', 'CAD/CAM', 'Prototype Development'] },
  { id: 's8', name: 'Komal Singh', rollNumber: 'NIT/CI/2024/003', department: 'Civil Engineering', year: 2, universityId: 'nit-jamshedpur', skills: ['STAAD Pro', 'Concrete Testing', 'Survey'] },
  { id: 's9', name: 'Ajay Kumar', rollNumber: 'ISM/CS/2023/066', department: 'Computer Science', year: 3, universityId: 'iit-ism-dhanbad', skills: ['Deep Learning', 'Computer Vision', 'TensorFlow'] },
  { id: 's10', name: 'Ritu Devi', rollNumber: 'ISM/EN/2023/028', department: 'Environmental Engineering', year: 3, universityId: 'iit-ism-dhanbad', skills: ['Sensor Calibration', 'Data Logging', 'Field Research'] },
  { id: 's11', name: 'Sanjay Besra', rollNumber: 'BIT/CE/2024/011', department: 'Civil Engineering', year: 2, universityId: 'bit-mesra', skills: ['Hydrology', 'AutoCAD', 'GPS Surveying'] },
  { id: 's12', name: 'Pallavi Gupta', rollNumber: 'BIT/CS/2023/089', department: 'Computer Science', year: 3, universityId: 'bit-mesra', skills: ['Data Science', 'R Programming', 'Statistical Analysis'] },
  { id: 's13', name: 'Vishal Yadav', rollNumber: 'NIT/EE/2023/037', department: 'Electrical Engineering', year: 3, universityId: 'nit-jamshedpur', skills: ['PLC Programming', 'SCADA', 'Power Systems'] },
  { id: 's14', name: 'Nisha Toppo', rollNumber: 'RU/CS/2023/012', department: 'Computer Applications', year: 3, universityId: 'ranchi-university', skills: ['Web Development', 'PHP', 'MySQL'] },
  { id: 's15', name: 'Ravi Prasad', rollNumber: 'BIT/ME/2022/004', department: 'Mechanical Engineering', year: 4, universityId: 'bit-mesra', skills: ['Welding', 'Manufacturing', 'Product Design'] },
  { id: 's16', name: 'Meena Giri', rollNumber: 'BAU/AG/2023/021', department: 'Agronomy', year: 3, universityId: 'bau-ranchi', skills: ['Soil Testing', 'Crop Management', 'Organic Farming'] },
  { id: 's17', name: 'Arun Hansda', rollNumber: 'ISM/MN/2023/041', department: 'Mining Engineering', year: 3, universityId: 'iit-ism-dhanbad', skills: ['Mine Planning', 'Safety Systems', 'Environmental Monitoring'] },
  { id: 's18', name: 'Divya Sharma', rollNumber: 'BIT/AR/2023/006', department: 'Architecture', year: 3, universityId: 'bit-mesra', skills: ['AutoCAD Architecture', 'Space Planning', 'Sustainable Design'] },
  { id: 's19', name: 'Suresh Mandal', rollNumber: 'NIT/CS/2024/027', department: 'Computer Science', year: 2, universityId: 'nit-jamshedpur', skills: ['Cloud Computing', 'DevOps', 'Python'] },
  { id: 's20', name: 'Pooja Barnwal', rollNumber: 'BIT/BT/2023/014', department: 'Biotechnology', year: 3, universityId: 'bit-mesra', skills: ['Microbiology', 'Water Analysis', 'Lab Testing'] },
  { id: 's21', name: 'Gaurav Thakur', rollNumber: 'ISM/CS/2022/033', department: 'Computer Science', year: 4, universityId: 'iit-ism-dhanbad', skills: ['NLP', 'AI Research', 'Sensor Fusion'] },
  { id: 's22', name: 'Lata Kumari', rollNumber: 'RU/SW/2023/008', department: 'Social Work', year: 3, universityId: 'ranchi-university', skills: ['Community Surveys', 'Field Research', 'Report Writing'] },
  { id: 's23', name: 'Prakash Munda', rollNumber: 'BIT/CE/2023/056', department: 'Civil Engineering', year: 3, universityId: 'bit-mesra', skills: ['Structural Analysis', 'Construction Management', 'Road Design'] },
  { id: 's24', name: 'Swati Jha', rollNumber: 'NIT/CS/2023/071', department: 'Computer Science', year: 3, universityId: 'nit-jamshedpur', skills: ['Mobile App Development', 'Flutter', 'Firebase'] },
  { id: 's25', name: 'Alok Tiwari', rollNumber: 'BIT/EE/2022/019', department: 'Electronics Engineering', year: 4, universityId: 'bit-mesra', skills: ['PCB Design', 'Embedded C', 'IoT Hardware'] },
  { id: 's26', name: 'Ranjana Singh', rollNumber: 'BAU/HS/2023/003', department: 'Horticulture', year: 3, universityId: 'bau-ranchi', skills: ['Plant Science', 'Greenhouse Management', 'Organic Certification'] },
  { id: 's27', name: 'Vikash Rana', rollNumber: 'BIT/CS/2022/087', department: 'Computer Science', year: 4, universityId: 'bit-mesra', skills: ['Full Stack Development', 'Node.js', 'PostgreSQL'] },
  { id: 's28', name: 'Anita Kachhap', rollNumber: 'RIMS/PH/2023/015', department: 'Public Health', year: 3, universityId: 'rims', skills: ['Epidemiology', 'Health Surveys', 'Statistical Analysis'] },
  { id: 's29', name: 'Ritesh Agarwal', rollNumber: 'NIT/ME/2022/062', department: 'Mechanical Engineering', year: 4, universityId: 'nit-jamshedpur', skills: ['Robotics', 'CNC Programming', 'Materials Testing'] },
  { id: 's30', name: 'Sushma Devi', rollNumber: 'BIT/EN/2024/022', department: 'Environmental Engineering', year: 2, universityId: 'bit-mesra', skills: ['Water Chemistry', 'Environmental Impact Assessment', 'GIS Basics'] },
];

// ─── INDUSTRY PARTNERS ───────────────────────────────────────────────────────

export const industryPartners: IndustryPartner[] = [
  { id: 'ip1', name: 'TechSolve Solutions Pvt. Ltd.', shortName: 'TechSolve', sector: 'Technology', headquarters: 'Ranchi', expertise: ['IoT', 'Embedded Systems', 'Cloud Platforms'], supportTypes: ['technology', 'mentorship', 'testing'], activeCollaborations: 3, totalFunding: 450000, impactProjects: 5, matchScore: 91 },
  { id: 'ip2', name: 'AquaSense Technologies', shortName: 'AquaSense', sector: 'Water Technology', headquarters: 'Bengaluru', expertise: ['Water Sensors', 'Real-time Monitoring', 'Data Analytics'], supportTypes: ['technology', 'equipment', 'testing'], activeCollaborations: 2, totalFunding: 380000, impactProjects: 4, matchScore: 95 },
  { id: 'ip3', name: 'GreenPath Innovations', shortName: 'GreenPath', sector: 'Clean Tech', headquarters: 'Dhanbad', expertise: ['Waste Management', 'Recycling Tech', 'Solar Energy'], supportTypes: ['funding', 'technology', 'csr'], activeCollaborations: 4, totalFunding: 620000, impactProjects: 7, matchScore: 78 },
  { id: 'ip4', name: 'Tata Steel Foundation', shortName: 'TSF', sector: 'CSR / Steel', headquarters: 'Jamshedpur', expertise: ['Community Development', 'Skill Training', 'Infrastructure'], supportTypes: ['funding', 'csr', 'deployment'], activeCollaborations: 6, totalFunding: 2800000, impactProjects: 12, matchScore: 82 },
  { id: 'ip5', name: 'Jharkhand Startups Hub', shortName: 'JSHub', sector: 'Startup Ecosystem', headquarters: 'Ranchi', expertise: ['Startup Mentorship', 'MVP Development', 'Funding Access'], supportTypes: ['mentorship', 'funding'], activeCollaborations: 8, totalFunding: 500000, impactProjects: 9, matchScore: 74 },
  { id: 'ip6', name: 'AgriTech Pvt. Ltd.', shortName: 'AgriTech', sector: 'Agriculture', headquarters: 'Ranchi', expertise: ['Precision Agriculture', 'Soil Sensors', 'Drone Technology'], supportTypes: ['technology', 'equipment', 'testing'], activeCollaborations: 3, totalFunding: 290000, impactProjects: 5, matchScore: 86 },
  { id: 'ip7', name: 'MediConnect Health Solutions', shortName: 'MediConnect', sector: 'Healthcare', headquarters: 'Ranchi', expertise: ['Telemedicine', 'Health Data', 'Mobile Health'], supportTypes: ['technology', 'mentorship', 'deployment'], activeCollaborations: 2, totalFunding: 180000, impactProjects: 3, matchScore: 71 },
  { id: 'ip8', name: 'Solar Energy Jharkhand', shortName: 'SEJ', sector: 'Renewable Energy', headquarters: 'Ranchi', expertise: ['Solar Panels', 'Battery Storage', 'Rural Electrification'], supportTypes: ['equipment', 'technology', 'deployment'], activeCollaborations: 5, totalFunding: 750000, impactProjects: 8, matchScore: 67 },
  { id: 'ip9', name: 'DataBridge Analytics', shortName: 'DataBridge', sector: 'Data Analytics', headquarters: 'Pune', expertise: ['Big Data', 'Predictive Analytics', 'Dashboard Design'], supportTypes: ['technology', 'mentorship'], activeCollaborations: 1, totalFunding: 120000, impactProjects: 2, matchScore: 79 },
  { id: 'ip10', name: 'RuralNet Communications', shortName: 'RuralNet', sector: 'Telecom', headquarters: 'Ranchi', expertise: ['Rural Connectivity', 'LoRaWAN', 'Mesh Networks'], supportTypes: ['technology', 'equipment', 'deployment'], activeCollaborations: 3, totalFunding: 340000, impactProjects: 4, matchScore: 88 },
  { id: 'ip11', name: 'Cleanwater India Foundation', shortName: 'CWIF', sector: 'Social Enterprise', headquarters: 'Delhi', expertise: ['Water Purification', 'Community Training', 'Impact Measurement'], supportTypes: ['funding', 'mentorship', 'csr'], activeCollaborations: 2, totalFunding: 560000, impactProjects: 6, matchScore: 93 },
  { id: 'ip12', name: 'Buildcraft Construction', shortName: 'Buildcraft', sector: 'Construction', headquarters: 'Bokaro', expertise: ['Rural Infrastructure', 'Road Construction', 'Community Buildings'], supportTypes: ['manufacturing', 'deployment', 'equipment'], activeCollaborations: 4, totalFunding: 890000, impactProjects: 7, matchScore: 65 },
  { id: 'ip13', name: 'EduTech Pathshala', shortName: 'Pathshala', sector: 'Education Technology', headquarters: 'Ranchi', expertise: ['Digital Learning', 'Teacher Training', 'Rural Ed-Tech'], supportTypes: ['technology', 'mentorship', 'csr'], activeCollaborations: 3, totalFunding: 230000, impactProjects: 4, matchScore: 58 },
  { id: 'ip14', name: 'NTPC Foundation', shortName: 'NTPC Fdn', sector: 'Power / CSR', headquarters: 'Hazaribagh', expertise: ['Rural Electrification', 'Community Development', 'Skill Training'], supportTypes: ['funding', 'csr', 'equipment'], activeCollaborations: 5, totalFunding: 1200000, impactProjects: 9, matchScore: 72 },
  { id: 'ip15', name: 'StartupBox Jharkhand', shortName: 'StartupBox', sector: 'Startup Incubator', headquarters: 'Ranchi', expertise: ['Product Development', 'Scaling', 'Go-to-Market'], supportTypes: ['mentorship', 'funding', 'testing'], activeCollaborations: 6, totalFunding: 480000, impactProjects: 8, matchScore: 69 },
];

// ─── CHALLENGES ───────────────────────────────────────────────────────────────

export const challenges: Challenge[] = [
  {
    id: 'JS-JH-2026-001284',
    title: 'Unsafe Drinking Water in Rural Community',
    description: 'Residents of Bero block in Ranchi district are facing severe drinking water contamination. Groundwater tests show elevated levels of arsenic and iron, causing health problems especially among children and pregnant women. Hand pumps are the primary water source for 8 villages and most have failed basic quality standards.',
    category: 'water',
    subcategory: 'Drinking Water Quality',
    district: 'Ranchi',
    block: 'Bero',
    village: 'Konka Toli',
    landmark: 'Near Bero Middle School',
    lat: 23.3441,
    lng: 85.3096,
    status: 'university_matching',
    priority: 'high',
    priorityScore: 87,
    aiConfidence: 94,
    peopleAffected: 1200,
    frequency: 'daily',
    severity: 'high',
    affectedGroups: ['Children', 'Women', 'Elderly', 'General Public'],
    communityConfirmations: 127,
    submittedBy: 'Rajiv Oraon',
    submittedAt: '2026-09-01T09:14:00Z',
    updatedAt: '2026-09-18T14:30:00Z',
    aiAnalysis: {
      domain: 'Water Resources',
      subdomain: 'Drinking Water Quality',
      confidence: 94,
      priorityScore: 87,
      priorityBreakdown: { severity: 30, affectedPopulation: 24, communityValidation: 18, frequency: 10, strategicRelevance: 5 },
      requiredExpertise: ['Civil Engineering', 'Environmental Engineering', 'IoT', 'Data Science'],
      suggestedStakeholders: ['Government Water Department', 'Environmental Research Department', 'Water Technology Startup'],
      sdgAlignment: [{ goal: 6, name: 'Clean Water & Sanitation' }, { goal: 3, name: 'Good Health & Well-being' }],
      similarChallengeIds: ['JS-JH-2026-000891', 'JS-JH-2026-000643', 'JS-JH-2026-000412'],
    },
    similarChallenges: ['JS-JH-2026-000891', 'JS-JH-2026-000643', 'JS-JH-2026-000412'],
    assignedUniversity: 'bit-mesra',
    projectId: 'PROJ-2026-0018',
    timeline: [
      { id: 't1', date: '2026-09-01', time: '09:14', actor: 'Rajiv Oraon', actorRole: 'Citizen', action: 'Challenge submitted via mobile app', type: 'submission' },
      { id: 't2', date: '2026-09-01', time: '09:17', actor: 'AI System', actorRole: 'System', action: 'AI analysis completed — Priority: High, Score: 87/100', type: 'system' },
      { id: 't3', date: '2026-09-03', time: '11:45', actor: 'Community', actorRole: 'Citizens', action: '127 community members confirmed the challenge', type: 'validation' },
      { id: 't4', date: '2026-09-08', time: '15:20', actor: 'Sh. A.K. Pandey', actorRole: 'Government Officer', action: 'Challenge validated by District Collector, Ranchi', type: 'validation' },
      { id: 't5', date: '2026-09-12', time: '10:00', actor: 'AI Matching System', actorRole: 'System', action: 'BIT Mesra matched at 94% — assignment recommended', type: 'assignment' },
      { id: 't6', date: '2026-09-15', time: '14:30', actor: 'Dr. Anjali Sharma', actorRole: 'Faculty', action: 'BIT Mesra accepted challenge — project creation initiated', type: 'assignment' },
    ],
    sdgAlignment: [6, 3],
  },
  {
    id: 'JS-JH-2026-000891',
    title: 'Unsafe Water in Village Panposh',
    description: 'Groundwater contamination with arsenic detected in Panposh area. Multiple families affected with chronic health issues.',
    category: 'water',
    subcategory: 'Groundwater Contamination',
    district: 'Ranchi',
    block: 'Angara',
    village: 'Panposh',
    lat: 23.2934,
    lng: 85.2874,
    status: 'government_validation',
    priority: 'high',
    priorityScore: 79,
    aiConfidence: 91,
    peopleAffected: 840,
    frequency: 'daily',
    severity: 'high',
    affectedGroups: ['Children', 'Women', 'General Public'],
    communityConfirmations: 89,
    submittedBy: 'Priya Devi',
    submittedAt: '2026-08-18T11:22:00Z',
    updatedAt: '2026-09-10T09:00:00Z',
    timeline: [
      { id: 't1', date: '2026-08-18', time: '11:22', actor: 'Priya Devi', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
      { id: 't2', date: '2026-08-18', time: '11:25', actor: 'AI System', actorRole: 'System', action: 'AI analysis completed', type: 'system' },
    ],
  },
  {
    id: 'JS-JH-2026-000643',
    title: 'Groundwater Quality Issue Near Mines',
    description: 'Mining activity in the region has contaminated nearby water sources. Residents using well water report metallic taste and discoloration.',
    category: 'water',
    subcategory: 'Industrial Contamination',
    district: 'Dhanbad',
    block: 'Jharia',
    village: 'Kenduadih',
    lat: 23.7841,
    lng: 86.4012,
    status: 'project_created',
    priority: 'critical',
    priorityScore: 91,
    aiConfidence: 88,
    peopleAffected: 2400,
    frequency: 'daily',
    severity: 'critical',
    affectedGroups: ['General Public', 'Workers', 'Children'],
    communityConfirmations: 203,
    submittedBy: 'Ramu Mahato',
    submittedAt: '2026-07-14T08:30:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
    projectId: 'PROJ-2026-0009',
    timeline: [
      { id: 't1', date: '2026-07-14', time: '08:30', actor: 'Ramu Mahato', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-000412',
    title: 'Water Contamination Near Primary School',
    description: 'The school water supply tests positive for E.coli and other bacteria. Children are falling ill regularly.',
    category: 'water',
    subcategory: 'Drinking Water Safety',
    district: 'Bokaro',
    block: 'Bermo',
    village: 'Ramgarh',
    lat: 23.6453,
    lng: 86.1234,
    status: 'deployed',
    priority: 'critical',
    priorityScore: 95,
    aiConfidence: 97,
    peopleAffected: 450,
    frequency: 'daily',
    severity: 'critical',
    affectedGroups: ['Children', 'Students'],
    communityConfirmations: 156,
    submittedBy: 'Headmaster S. Kumar',
    submittedAt: '2026-05-02T07:45:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
    projectId: 'PROJ-2026-0003',
    timeline: [
      { id: 't1', date: '2026-05-02', time: '07:45', actor: 'S. Kumar', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-001102',
    title: 'Waste Disposal Site Near Residential Area',
    description: 'Unmanaged municipal solid waste dumped near housing colony causing health hazards, foul smell and mosquito breeding.',
    category: 'waste',
    subcategory: 'Solid Waste Management',
    district: 'Dhanbad',
    block: 'Dhanbad Sadar',
    village: 'Bank More',
    lat: 23.8012,
    lng: 86.4534,
    status: 'community_validation',
    priority: 'medium',
    priorityScore: 68,
    aiConfidence: 89,
    peopleAffected: 3200,
    frequency: 'daily',
    severity: 'medium',
    affectedGroups: ['General Public', 'Children', 'Elderly'],
    communityConfirmations: 312,
    submittedBy: 'Meena Gupta',
    submittedAt: '2026-09-10T13:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
    timeline: [
      { id: 't1', date: '2026-09-10', time: '13:00', actor: 'Meena Gupta', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-001056',
    title: 'Broken Community Road Affecting Village Connectivity',
    description: 'The main road connecting Bokaro block village to the district highway has been severely damaged for over 6 months causing transportation difficulties for villagers.',
    category: 'infrastructure',
    subcategory: 'Road Connectivity',
    district: 'Bokaro',
    block: 'Bokaro Sadar',
    village: 'Chandankiari',
    lat: 23.7012,
    lng: 86.1890,
    status: 'resolved',
    priority: 'high',
    priorityScore: 82,
    aiConfidence: 92,
    peopleAffected: 680,
    frequency: 'daily',
    severity: 'high',
    affectedGroups: ['General Public', 'Farmers', 'Students', 'Workers'],
    communityConfirmations: 78,
    submittedBy: 'Raju Singh',
    submittedAt: '2026-06-15T10:30:00Z',
    updatedAt: '2026-09-05T16:00:00Z',
    timeline: [
      { id: 't1', date: '2026-06-15', time: '10:30', actor: 'Raju Singh', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-000987',
    title: 'Lack of Electricity in Remote Village',
    description: '3 hamlets in Palamu district have no electricity connection for the past 12 years. Solar energy solution requested.',
    category: 'energy',
    subcategory: 'Rural Electrification',
    district: 'Palamu',
    block: 'Chainpur',
    village: 'Lalpania',
    lat: 24.0123,
    lng: 84.0234,
    status: 'pilot',
    priority: 'high',
    priorityScore: 84,
    aiConfidence: 91,
    peopleAffected: 320,
    frequency: 'daily',
    severity: 'high',
    affectedGroups: ['General Public', 'Children', 'Women', 'Students'],
    communityConfirmations: 98,
    submittedBy: 'Birsa Munda',
    submittedAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
    projectId: 'PROJ-2026-0011',
    timeline: [
      { id: 't1', date: '2026-07-20', time: '09:00', actor: 'Birsa Munda', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-001201',
    title: 'Absence of Healthcare Facility in Tribal Village',
    description: 'Nearest primary health centre is 28 km away. Tribal community in Simdega district has no access to basic healthcare. Women deliver babies at home without medical support.',
    category: 'healthcare',
    subcategory: 'Rural Healthcare Access',
    district: 'Simdega',
    block: 'Kolebira',
    village: 'Amgachi',
    lat: 22.6234,
    lng: 84.5123,
    status: 'government_validation',
    priority: 'critical',
    priorityScore: 93,
    aiConfidence: 96,
    peopleAffected: 1800,
    frequency: 'daily',
    severity: 'critical',
    affectedGroups: ['Women', 'Children', 'Elderly', 'General Public'],
    communityConfirmations: 241,
    submittedBy: 'ASHA Worker Kamala',
    submittedAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-19T14:00:00Z',
    timeline: [
      { id: 't1', date: '2026-09-05', time: '08:00', actor: 'ASHA Worker Kamala', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-000734',
    title: 'Crop Failure Due to Soil Degradation',
    description: 'Repeated use of chemical fertilizers has severely degraded soil quality in Deoghar district. Crop yields have fallen by 40% in the past 3 years.',
    category: 'agriculture',
    subcategory: 'Soil Health',
    district: 'Deoghar',
    block: 'Sarwan',
    village: 'Bhimpur',
    lat: 24.4765,
    lng: 86.7012,
    status: 'in_progress',
    priority: 'high',
    priorityScore: 78,
    aiConfidence: 87,
    peopleAffected: 2600,
    frequency: 'regular',
    severity: 'high',
    affectedGroups: ['Farmers'],
    communityConfirmations: 167,
    submittedBy: 'Ramesh Farmer Group',
    submittedAt: '2026-07-28T11:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
    projectId: 'PROJ-2026-0014',
    timeline: [
      { id: 't1', date: '2026-07-28', time: '11:00', actor: 'Ramesh Farmer Group', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-001189',
    title: 'School Dropout Due to Lack of Digital Learning',
    description: 'Students in Dumka district are unable to access quality education due to lack of digital infrastructure. 60% of class 9-10 students dropout annually.',
    category: 'education',
    subcategory: 'Digital Literacy',
    district: 'Dumka',
    block: 'Masalia',
    village: 'Pachhiyari',
    lat: 24.2834,
    lng: 87.2123,
    status: 'university_matching',
    priority: 'high',
    priorityScore: 81,
    aiConfidence: 89,
    peopleAffected: 1400,
    frequency: 'regular',
    severity: 'high',
    affectedGroups: ['Students', 'Children'],
    communityConfirmations: 134,
    submittedBy: 'Teacher Prabha Sinha',
    submittedAt: '2026-08-30T09:30:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
    timeline: [
      { id: 't1', date: '2026-08-30', time: '09:30', actor: 'Teacher Prabha Sinha', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-001045',
    title: 'Deforestation and Loss of Forest Cover',
    description: 'Illegal tree felling destroying forest ecosystem in Latehar district. Local tribal communities depend on forests for livelihood and the destruction is accelerating.',
    category: 'environment',
    subcategory: 'Deforestation',
    district: 'Latehar',
    block: 'Latehar Sadar',
    village: 'Jaladag',
    lat: 23.7512,
    lng: 84.5123,
    status: 'government_validation',
    priority: 'critical',
    priorityScore: 88,
    aiConfidence: 93,
    peopleAffected: 4500,
    frequency: 'daily',
    severity: 'critical',
    affectedGroups: ['Farmers', 'General Public', 'Rural Livelihood'],
    communityConfirmations: 289,
    submittedBy: 'Forest Community Leader',
    submittedAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-09-17T09:00:00Z',
    timeline: [
      { id: 't1', date: '2026-08-22', time: '10:00', actor: 'Forest Community Leader', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
  {
    id: 'JS-JH-2026-000556',
    title: 'Flood Early Warning System Needed',
    description: 'Annual floods in Sahebganj district cause massive damage with no advance warning system available. Lives are lost and crops destroyed every monsoon.',
    category: 'environment',
    subcategory: 'Flood Management',
    district: 'East Singhbhum',
    block: 'Boram',
    village: 'Ghagra',
    lat: 22.8234,
    lng: 86.2123,
    status: 'deployed',
    priority: 'critical',
    priorityScore: 96,
    aiConfidence: 98,
    peopleAffected: 8200,
    frequency: 'occasional',
    severity: 'critical',
    affectedGroups: ['General Public', 'Farmers', 'Children', 'Elderly'],
    communityConfirmations: 523,
    submittedBy: 'Village Panchayat',
    submittedAt: '2026-04-10T07:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
    projectId: 'PROJ-2026-0001',
    timeline: [
      { id: 't1', date: '2026-04-10', time: '07:00', actor: 'Village Panchayat', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' },
    ],
  },
];

// Fill with additional mock challenges (simplified)
const additionalChallenges: Partial<Challenge>[] = [
  { id: 'JS-JH-2026-001150', title: 'Stagnant Water and Mosquito Breeding', category: 'healthcare', district: 'Hazaribagh', block: 'Barhi', village: 'Tanrar', status: 'community_validation', priority: 'medium', peopleAffected: 890, communityConfirmations: 67, priorityScore: 65, aiConfidence: 84 },
  { id: 'JS-JH-2026-001130', title: 'Open Defecation in Rural Area', category: 'healthcare', district: 'Palamu', block: 'Hariharganj', village: 'Dhibra', status: 'government_validation', priority: 'high', peopleAffected: 1100, communityConfirmations: 142, priorityScore: 76, aiConfidence: 90 },
  { id: 'JS-JH-2026-001120', title: 'Agricultural Market Access Problem', category: 'agriculture', district: 'Giridih', block: 'Bagodar', village: 'Sirka', status: 'in_progress', priority: 'medium', peopleAffected: 1800, communityConfirmations: 98, priorityScore: 70, aiConfidence: 82 },
  { id: 'JS-JH-2026-001098', title: 'Street Lighting Failure in Town', category: 'infrastructure', district: 'Dhanbad', block: 'Jharia', village: 'Jharia Town', status: 'resolved', priority: 'low', peopleAffected: 4500, communityConfirmations: 367, priorityScore: 55, aiConfidence: 78 },
  { id: 'JS-JH-2026-001087', title: 'Lack of Clean Cooking Fuel', category: 'energy', district: 'Gumla', block: 'Sisai', village: 'Nagri', status: 'university_matching', priority: 'medium', peopleAffected: 560, communityConfirmations: 45, priorityScore: 69, aiConfidence: 83 },
  { id: 'JS-JH-2026-001078', title: 'Tribal Language Education Gap', category: 'education', district: 'Simdega', block: 'Thethaitangar', village: 'Bhinsa', status: 'project_created', priority: 'medium', peopleAffected: 720, communityConfirmations: 89, priorityScore: 72, aiConfidence: 86 },
  { id: 'JS-JH-2026-001065', title: 'Rainwater Harvesting System Needed', category: 'water', district: 'Hazaribagh', block: 'Vishnugarh', village: 'Tiril', status: 'in_progress', priority: 'high', peopleAffected: 980, communityConfirmations: 76, priorityScore: 80, aiConfidence: 88 },
  { id: 'JS-JH-2026-001054', title: 'Inaccessible School Building for Disabled', category: 'accessibility', district: 'Bokaro', block: 'Gomia', village: 'Nawadih', status: 'deployed', priority: 'medium', peopleAffected: 34, communityConfirmations: 28, priorityScore: 74, aiConfidence: 91 },
  { id: 'JS-JH-2026-001043', title: 'Plastic Waste in River', category: 'environment', district: 'Ranchi', block: 'Ratu', village: 'Ratu Chowk', status: 'community_validation', priority: 'medium', peopleAffected: 5600, communityConfirmations: 234, priorityScore: 71, aiConfidence: 87 },
  { id: 'JS-JH-2026-001032', title: 'Lack of Cold Storage for Farmers', category: 'agriculture', district: 'Deoghar', block: 'Mohanpur', village: 'Lalmatia', status: 'pilot', priority: 'high', peopleAffected: 2300, communityConfirmations: 178, priorityScore: 79, aiConfidence: 85 },
  { id: 'JS-JH-2026-001021', title: 'Bridge Washout During Monsoon', category: 'infrastructure', district: 'West Singhbhum', block: 'Chakradharpur', village: 'Rajkharswan', status: 'government_validation', priority: 'critical', peopleAffected: 1400, communityConfirmations: 198, priorityScore: 91, aiConfidence: 93 },
  { id: 'JS-JH-2026-001010', title: 'Rural Women Skill Development Gap', category: 'rural_livelihood', district: 'Palamu', block: 'Satbarwa', village: 'Jhariya', status: 'in_progress', priority: 'medium', peopleAffected: 840, communityConfirmations: 56, priorityScore: 67, aiConfidence: 80 },
  { id: 'JS-JH-2026-000999', title: 'Mining Dust Affecting Respiratory Health', category: 'healthcare', district: 'Dhanbad', block: 'Tundi', village: 'Barharwa Lakhansara', status: 'project_created', priority: 'high', peopleAffected: 3200, communityConfirmations: 287, priorityScore: 86, aiConfidence: 92 },
  { id: 'JS-JH-2026-000988', title: 'Soil Erosion Damaging Agricultural Land', category: 'agriculture', district: 'Dumka', block: 'Jama', village: 'Ladam', status: 'university_matching', priority: 'high', peopleAffected: 1700, communityConfirmations: 123, priorityScore: 77, aiConfidence: 84 },
  { id: 'JS-JH-2026-000976', title: 'Lack of Internet in School', category: 'education', district: 'Giridih', block: 'Bengabad', village: 'Sirka', status: 'in_progress', priority: 'medium', peopleAffected: 380, communityConfirmations: 42, priorityScore: 68, aiConfidence: 81 },
];

// Merge all challenges
export const allChallenges: Challenge[] = [
  ...challenges,
  ...additionalChallenges.map(c => ({
    id: c.id || '',
    title: c.title || '',
    description: `Community-reported challenge requiring attention in ${c.district} district.`,
    category: c.category as ChallengeCategory || 'infrastructure',
    subcategory: 'General',
    district: c.district || 'Ranchi',
    block: c.block || '',
    village: c.village || '',
    lat: 23.3441 + (Math.random() - 0.5) * 2,
    lng: 85.3096 + (Math.random() - 0.5) * 2,
    status: c.status || 'submitted',
    priority: c.priority as ChallengePriority || 'medium',
    priorityScore: c.priorityScore || 70,
    aiConfidence: c.aiConfidence || 80,
    peopleAffected: c.peopleAffected || 500,
    frequency: 'regular' as const,
    severity: 'medium' as const,
    affectedGroups: ['General Public'],
    communityConfirmations: c.communityConfirmations || 30,
    submittedBy: 'Community Member',
    submittedAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
    timeline: [{ id: 't1', date: '2026-08-01', time: '10:00', actor: 'Community Member', actorRole: 'Citizen', action: 'Challenge submitted', type: 'submission' as const }],
  })),
];

// ─── PROJECTS ─────────────────────────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: 'PROJ-2026-0018',
    name: 'Smart Rural Water Monitoring System',
    challengeId: 'JS-JH-2026-001284',
    universityId: 'bit-mesra',
    status: 'prototype',
    progress: 64,
    facultyMentorId: 'f1',
    studentIds: ['s1', 's2', 's3', 's4', 's5'],
    industryPartnerId: 'ip1',
    description: 'IoT-based real-time water quality monitoring system for rural communities in Ranchi district using low-cost sensors and cloud analytics.',
    solution: 'Deploy 24 IoT sensor nodes across 8 villages monitoring arsenic, iron, pH, turbidity. Data streams to cloud dashboard accessible by government and community.',
    technology: ['IoT', 'LoRaWAN', 'AWS IoT', 'React Dashboard', 'Machine Learning'],
    expectedOutcome: '4,800 people with safe, monitored water; automated alerts for contamination events',
    startDate: '2026-09-18',
    expectedEndDate: '2027-03-15',
    milestones: [
      { id: 'm1', title: 'Research & Requirements', description: 'Literature review, site visits, requirement gathering', status: 'completed', owner: 'Dr. Anjali Sharma', deadline: '2026-10-01', progress: 100, documents: ['requirements.pdf', 'site_survey.pdf'] },
      { id: 'm2', title: 'Sensor Design & Prototype', description: 'Design IoT sensor hardware, build first prototype', status: 'completed', owner: 'Aman Sinha', deadline: '2026-10-20', progress: 100 },
      { id: 'm3', title: 'Field Testing', description: 'Deploy 3 pilot sensors, validate data accuracy', status: 'in_progress', owner: 'Rahul Kumar', deadline: '2026-11-10', progress: 45, documents: ['field_test_plan.pdf'] },
      { id: 'm4', title: 'Pilot Deployment', description: 'Deploy all 24 sensors across 8 villages', status: 'pending', owner: 'Prof. Rajesh Kumar', deadline: '2026-12-15', progress: 0 },
      { id: 'm5', title: 'Impact Assessment', description: 'Measure water quality improvement, community health data', status: 'pending', owner: 'Dr. Anjali Sharma', deadline: '2027-02-15', progress: 0 },
    ],
    timeline: [
      { id: 't1', date: '2026-09-18', time: '10:00', actor: 'BIT Mesra', actorRole: 'University', action: 'Project created and team assembled', type: 'milestone' },
      { id: 't2', date: '2026-09-22', time: '14:00', actor: 'TechSolve Solutions', actorRole: 'Industry', action: 'Industry partner joined — providing IoT hardware and mentorship', type: 'collaboration' },
      { id: 't3', date: '2026-10-01', time: '09:00', actor: 'Rahul Kumar', actorRole: 'Student', action: 'Milestone 1 completed: Research & Requirements', type: 'milestone' },
      { id: 't4', date: '2026-10-20', time: '11:00', actor: 'Aman Sinha', actorRole: 'Student', action: 'Milestone 2 completed: Prototype built and tested', type: 'milestone' },
      { id: 't5', date: '2026-10-28', time: '15:00', actor: 'Government Water Department', actorRole: 'Government', action: 'Government approved field testing in Konka Toli village', type: 'validation' },
    ],
    peopleImpacted: 4800,
    villagesCovered: 8,
    estimatedSavings: 240000,
    jobsCreated: 4,
    pilotLocation: 'Bero Block, Ranchi',
  },
  {
    id: 'PROJ-2026-0001',
    name: 'AI Flood Early Warning System',
    challengeId: 'JS-JH-2026-000556',
    universityId: 'jsac',
    status: 'impact',
    progress: 100,
    facultyMentorId: 'f10',
    studentIds: ['s9', 's21', 's17'],
    industryPartnerId: 'ip10',
    description: 'ML-based flood prediction system using satellite imagery and river sensor data to provide 48-hour advance warning to communities.',
    solution: 'Integration of ISRO satellite data, river gauges, and rainfall data with ML models for flood prediction.',
    technology: ['ML', 'GIS', 'Satellite Remote Sensing', 'LoRaWAN', 'SMS Alerts'],
    expectedOutcome: '12 villages covered with 48-hour advance warning',
    startDate: '2026-04-20',
    expectedEndDate: '2026-09-01',
    milestones: [
      { id: 'm1', title: 'Data Collection', description: 'Collect historical flood and satellite data', status: 'completed', owner: 'Dr. Sanjay Oraon', deadline: '2026-05-15', progress: 100 },
      { id: 'm2', title: 'ML Model Development', description: 'Train and validate prediction models', status: 'completed', owner: 'Ajay Kumar', deadline: '2026-06-30', progress: 100 },
      { id: 'm3', title: 'Sensor Deployment', description: 'Deploy river sensors and alert systems', status: 'completed', owner: 'RuralNet', deadline: '2026-07-31', progress: 100 },
      { id: 'm4', title: 'Pilot & Validation', description: 'Live pilot during 2026 monsoon', status: 'completed', owner: 'Dr. Sanjay Oraon', deadline: '2026-08-31', progress: 100 },
    ],
    timeline: [],
    peopleImpacted: 8200,
    villagesCovered: 12,
    estimatedSavings: 1800000,
    jobsCreated: 8,
    pilotLocation: 'East Singhbhum',
  },
  {
    id: 'PROJ-2026-0011',
    name: 'Solar Microgrid for Remote Villages',
    challengeId: 'JS-JH-2026-000987',
    universityId: 'bit-mesra',
    status: 'pilot',
    progress: 82,
    facultyMentorId: 'f11',
    studentIds: ['s15', 's25', 's13'],
    industryPartnerId: 'ip8',
    description: 'Community solar microgrid providing reliable 24x7 electricity to 3 unelectrified hamlets in Palamu.',
    solution: '15kW solar array with 48V battery bank, smart metering and prepaid system for each household.',
    technology: ['Solar PV', 'Battery Storage', 'Smart Meters', 'IoT Monitoring'],
    expectedOutcome: '320 people with 24x7 electricity; improved education and health outcomes',
    startDate: '2026-08-01',
    expectedEndDate: '2026-12-31',
    milestones: [
      { id: 'm1', title: 'Site Assessment', description: 'Solar resource assessment and load survey', status: 'completed', owner: 'Dr. Amit Ranjan', deadline: '2026-08-15', progress: 100 },
      { id: 'm2', title: 'System Design', description: 'Engineering design of microgrid system', status: 'completed', owner: 'Ravi Prasad', deadline: '2026-09-01', progress: 100 },
      { id: 'm3', title: 'Installation', description: 'Install panels, batteries and wiring', status: 'in_progress', owner: 'Solar Energy Jharkhand', deadline: '2026-10-31', progress: 70 },
      { id: 'm4', title: 'Pilot Operation', description: 'Monitor system for 60 days', status: 'pending', owner: 'Dr. Amit Ranjan', deadline: '2026-12-15', progress: 0 },
    ],
    timeline: [],
    peopleImpacted: 320,
    villagesCovered: 3,
    estimatedSavings: 85000,
    jobsCreated: 2,
    pilotLocation: 'Chainpur Block, Palamu',
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  { id: 'n1', title: 'Challenge Validated', message: 'Your challenge "Unsafe Drinking Water in Rural Community" has been validated by District Collector, Ranchi.', type: 'challenge', read: false, createdAt: '2026-09-08T15:20:00Z', link: '/citizen/challenges/JS-JH-2026-001284', forRole: ['citizen'] },
  { id: 'n2', title: 'University Match Found', message: 'BIT Mesra has been matched to your challenge with 94% compatibility.', type: 'challenge', read: false, createdAt: '2026-09-12T10:05:00Z', link: '/citizen/challenges/JS-JH-2026-001284', forRole: ['citizen'] },
  { id: 'n3', title: 'Community Milestone', message: '127 community members have confirmed your challenge. It has high community support.', type: 'challenge', read: true, createdAt: '2026-09-03T11:50:00Z', forRole: ['citizen'] },
  { id: 'n4', title: 'New Challenge Assigned', message: 'Challenge JS-JH-2026-001284 (Water Quality, Ranchi) has been assigned to your institution. 94% match score.', type: 'challenge', read: false, createdAt: '2026-09-12T10:10:00Z', link: '/university/challenges/JS-JH-2026-001284', forRole: ['university'] },
  { id: 'n5', title: 'Industry Partner Joined', message: 'TechSolve Solutions has offered technology support for your project "Smart Rural Water Monitoring System".', type: 'collaboration', read: false, createdAt: '2026-09-22T14:05:00Z', link: '/university/projects/PROJ-2026-0018', forRole: ['university'] },
  { id: 'n6', title: 'High-Priority Challenge Alert', message: '3 new critical challenges reported in Ranchi district requiring government validation.', type: 'challenge', read: false, createdAt: '2026-09-20T09:00:00Z', forRole: ['government'] },
  { id: 'n7', title: 'Pilot Success Report', message: 'AI Flood Warning System pilot in East Singhbhum successfully protected 8,200 people during monsoon.', type: 'milestone', read: false, createdAt: '2026-09-01T08:00:00Z', link: '/government/projects', forRole: ['government'] },
  { id: 'n8', title: 'New Collaboration Request', message: 'Project "Smart Rural Water Monitoring" from BIT Mesra seeks IoT hardware support. 91% match.', type: 'collaboration', read: false, createdAt: '2026-09-19T16:00:00Z', link: '/industry/opportunities', forRole: ['industry'] },
  { id: 'n9', title: 'Milestone Completed', message: 'Team has completed the Prototype Development milestone for Smart Rural Water Monitoring System.', type: 'milestone', read: true, createdAt: '2026-10-20T11:05:00Z', link: '/industry/projects/PROJ-2026-0018', forRole: ['industry'] },
  { id: 'n10', title: 'Government Approval Received', message: 'Field testing has been approved by the Government Water Department. You can now proceed to Konka Toli village.', type: 'project', read: false, createdAt: '2026-10-28T15:05:00Z', link: '/university/projects/PROJ-2026-0018', forRole: ['university'] },
];

export const MOCK_CHALLENGES = allChallenges;
export const MOCK_UNIVERSITIES = universities;
export const MOCK_INDUSTRY = industryPartners.map(i => ({
  ...i,
  focusAreas: ['Water Sanitation', 'Solar Microgrid', 'IoT Sensors', 'Rural Health'],
  totalFundingCommitted: i.totalFunding || 2500000
}));
export const MOCK_PROJECTS = projects.map(p => ({
  ...p,
  title: p.name || 'R&D Project',
  universityName: 'BIT Mesra',
  fundingAmount: 250000,
  fundingSource: 'CSR Grant',
  facultyLead: 'Prof. Alok Nath',
  studentTeam: ['Ananya Sharma', 'Rahul Verma', 'Sneha Roy']
}));
export const JHARKHAND_DISTRICTS = districts.map(d => ({
  ...d,
  population: 850000,
  headquarters: d.name,
  polygon: `${d.lat * 10 - 200},${d.lng * 10 - 800} ${d.lat * 10 - 180},${d.lng * 10 - 780} ${d.lat * 10 - 190},${d.lng * 10 - 750} ${d.lat * 10 - 210},${d.lng * 10 - 770}`,
  coordinates: { x: (d.lng - 84) * 80 + 50, y: (25 - d.lat) * 80 + 50 }
}));
export const MOCK_STUDENTS = students;
export const MOCK_FACULTY = faculty;
export const MOCK_NOTIFICATIONS = notifications;

